ERROR_Login = "Login failed!"
ERROR_Register = "Register failed!"
ERROR_Logout = "Logout failed!"
ERROR_GetUser = "Failed to get the current user!"
ERROR_Create = "Create failed!"
ERROR_Edit = "Edit failed!"
ERROR_Update = "Update failed!"
ERROR_Get = "Get failed!"
ERROR_Delete = "Deletion failed!"
ERROR_Clear = "Cleared failed!"
ERROR_Upload = "Upload failed!"
ERROR_Validate = "Validation failed"
ERROR_MESSAGE_GetToken = "Failed to get token!"
ERROR_MESSAGE_TokenVerificationFailed = "Token verification failed!"
ERROR_MESSAGE_CacheIsNotEnabled = "Cache is not enabled!"
ERROR_MESSAGE_PermissionDenied = "Insufficient permissions"
ERROR_MESSAGE_RegistrationClosed = "The administrator has closed the registration function!"
ERROR_MESSAGE_DuplicateUserName = "The user name already exists!"
ERROR_MESSAGE_DuplicateRoleName = "The current role name already exists!"
ERROR_MESSAGE_ProhibitOperationOfAdministratorUsers = "Prohibit operating administrator users!"
ERROR_MESSAGE_GetPermission = "Failed to obtain permission!"
ERROR_MESSAGE_PermissionNotRegistered = "Permission not registered!"
SUCCESS_Login = "Login successfully!"
SUCCESS_Logout = "Logout successfully!"
SUCCESS_GetUser = "Get the current user successfully!"
SUCCESS_Register = "Registered successfully!"
SUCCESS_Create = "Created successfully!"
SUCCESS_Edit = "Edit successfully!"
SUCCESS_Update = "Update successfully!"
SUCCESS_Get = "Get success!"
SUCCESS_Operation = "Successful operation!"
SUCCESS_Clear = "Cleared successfully!"
SUCCESS_Delete = "Delete successfully!"
SUCCESS_Upload = "Uploaded successfully!"
