ERROR_Login = "登录失败！"
ERROR_Register = "注册失败！"
ERROR_Logout = "登出失败！"
ERROR_GetUser = "获取当前用户失败！"
ERROR_Create = "创建失败！"
ERROR_Edit = "编辑失败！"
ERROR_Update = "更新失败！"
ERROR_Get = "获取失败！"
ERROR_Delete = "删除失败！"
ERROR_Clear = "清除失败！"
ERROR_Upload = "上传失败！"
ERROR_Validate = "验证失败"
ERROR_MESSAGE_GetToken = "获取令牌失败！"
ERROR_MESSAGE_TokenVerificationFailed = "令牌校验失败！"
ERROR_MESSAGE_CacheIsNotEnabled = "缓存未开启！"
ERROR_MESSAGE_PermissionDenied = "权限不足"
ERROR_MESSAGE_RegistrationClosed = "管理员关闭了注册功能"
ERROR_MESSAGE_DuplicateUserName = "用户名已存在！"
ERROR_MESSAGE_DuplicateRoleName = "当前角色名已存在！"
ERROR_MESSAGE_ProhibitOperationOfAdministratorUsers = "禁止操作管理员用户！"
ERROR_MESSAGE_GetPermission = "获取权限失败！"
ERROR_MESSAGE_PermissionNotRegistered = "权限未注册！"
ERROR_MESSAGE_CaptchaVerificationFailed = "当前页面已经过期，请刷新页面！"
SUCCESS_Login = "登录成功！"
SUCCESS_Logout = "登出成功！"
SUCCESS_GetUser = "获取当前用户成功！"
SUCCESS_Register = "注册成功！"
SUCCESS_Create = "创建成功！"
SUCCESS_Edit = "编辑成功！"
SUCCESS_Update = "更新成功！"
SUCCESS_Get = "获取成功！"
SUCCESS_Operation = "操作成功！"
SUCCESS_Validate = "验证成功！"
SUCCESS_Clear = "清除成功！"
SUCCESS_Delete = "删除成功！"
SUCCESS_Upload = "上传成功！"
